// Major yacht shows, boat shows, and regattas — EU & UK only
// Used for seasonal route planning and featured listings

export interface YachtEvent {
  id: string
  name: string
  location: string
  port: string
  country: string
  region: string
  month: number          // 1-12
  startDay: number       // typical start day
  durationDays: number
  type: 'boat_show' | 'regatta' | 'superyacht' | 'trade_show' | 'rally'
  tier: 'major' | 'regional' | 'local'
  description: string
  logistics: string      // tips for transporters
}

export const yachtEvents: YachtEvent[] = [
  // ─── MAJOR BOAT SHOWS ────────────────────────────────────────────────────

  {
    id: 'monaco-yacht-show',
    name: 'Monaco Yacht Show',
    location: 'Port Hercules, Monaco',
    port: 'Port Hercules',
    country: 'Monaco',
    region: 'French Riviera',
    month: 9,
    startDay: 25,
    durationDays: 4,
    type: 'superyacht',
    tier: 'major',
    description: 'The world\'s premier superyacht event. 125+ superyachts, 580+ exhibitors.',
    logistics: 'High demand 2 weeks before. Port access restricted — advance permits essential. Deliveries before 08:00 or after 20:00 only during show. Use Fontvieille or Cap d\'Ail for staging.',
  },
  {
    id: 'cannes-yachting-festival',
    name: 'Cannes Yachting Festival',
    location: 'Vieux Port & Port Canto, Cannes',
    port: 'Vieux Port de Cannes',
    country: 'France',
    region: 'French Riviera',
    month: 9,
    startDay: 10,
    durationDays: 6,
    type: 'boat_show',
    tier: 'major',
    description: 'Europe\'s largest in-water boat show. Split across two ports with 700+ boats.',
    logistics: 'Two port locations — confirm which one. Croisette road closures affect access. Early morning delivery slots only. Park at Lérins car park and use show shuttle.',
  },
  {
    id: 'southampton-boat-show',
    name: 'Southampton International Boat Show',
    location: 'Mayflower Park, Southampton',
    port: 'Southampton Marina',
    country: 'UK',
    region: 'South Coast',
    month: 9,
    startDay: 13,
    durationDays: 10,
    type: 'boat_show',
    tier: 'major',
    description: 'UK\'s biggest boat show with 500+ exhibitors and Europe\'s largest purpose-built marina.',
    logistics: 'Good M27 motorway access. Use exhibitor entrance on Town Quay. Loading bay slots must be pre-booked. No parking inside show ground.',
  },
  {
    id: 'boot-dusseldorf',
    name: 'boot Düsseldorf',
    location: 'Messe Düsseldorf, Germany',
    port: 'N/A — Exhibition Centre',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    month: 1,
    startDay: 18,
    durationDays: 9,
    type: 'boat_show',
    tier: 'major',
    description: 'World\'s largest indoor boat and watersports show. 250,000+ visitors, 1,900+ exhibitors.',
    logistics: 'Indoor venue — all deliveries via loading docks. Pre-book unloading slots via Messe portal. Hall numbers critical for correct dock assignment.',
  },
  {
    id: 'genoa-boat-show',
    name: 'Salone Nautico di Genova',
    location: 'Genoa Waterfront Marina, Italy',
    port: 'Porto Antico, Genova',
    country: 'Italy',
    region: 'Liguria',
    month: 9,
    startDay: 19,
    durationDays: 6,
    type: 'boat_show',
    tier: 'major',
    description: 'Italy\'s premier boat show, growing rapidly with 1,000+ brands.',
    logistics: 'ZTL (limited traffic zone) restrictions in Genoa centre. Use Fiera entrance for commercial vehicles. Overnight deliveries preferred.',
  },
  {
    id: 'palma-superyacht-show',
    name: 'Palma Superyacht Show',
    location: 'STP Shipyard, Palma de Mallorca',
    port: 'STP Shipyard Palma',
    country: 'Spain',
    region: 'Balearic Islands',
    month: 4,
    startDay: 27,
    durationDays: 4,
    type: 'superyacht',
    tier: 'major',
    description: 'Key superyacht refit and new-build showcase in the Med\'s biggest refit hub.',
    logistics: 'STP shipyard access pass required. Ferry from Barcelona or Denia for vehicle transport. Good early-season Med positioning.',
  },

  // ─── REGATTAS & SAILING EVENTS ───────────────────────────────────────────

  {
    id: 'les-voiles-st-tropez',
    name: 'Les Voiles de Saint-Tropez',
    location: 'Saint-Tropez, France',
    port: 'Port de Saint-Tropez',
    country: 'France',
    region: 'French Riviera',
    month: 9,
    startDay: 28,
    durationDays: 7,
    type: 'regatta',
    tier: 'major',
    description: 'Prestigious regatta with 300+ classic and modern yachts in the iconic port.',
    logistics: 'Saint-Tropez has no motorway access — single road in. Arrive before 07:00 or use Gassin bypass. Port parking extremely limited — use Place des Lices and walk in.',
  },
  {
    id: 'cowes-week',
    name: 'Cowes Week',
    location: 'Cowes, Isle of Wight',
    port: 'Cowes Yacht Haven',
    country: 'UK',
    region: 'South Coast',
    month: 7,
    startDay: 29,
    durationDays: 8,
    type: 'regatta',
    tier: 'major',
    description: 'Britain\'s oldest and most prestigious sailing regatta, 8,000+ competitors.',
    logistics: 'Vehicle ferry from Southampton or Lymington. Red Funnel freight service for commercial vehicles. Book ferry in advance — sells out. Limited parking in Cowes.',
  },
  {
    id: 'maxi-yacht-rolex-cup',
    name: 'Maxi Yacht Rolex Cup',
    location: 'Porto Cervo, Sardinia',
    port: 'Marina di Porto Cervo',
    country: 'Italy',
    region: 'Sardinia',
    month: 9,
    startDay: 1,
    durationDays: 6,
    type: 'regatta',
    tier: 'major',
    description: 'The world\'s premier maxi yacht regatta at the iconic Yacht Club Costa Smeralda.',
    logistics: 'Ferry from Civitavecchia, Genoa, or Livorno to Olbia. 30km drive from Olbia to Porto Cervo. Marina access restricted during regatta — use service entrance.',
  },
  {
    id: 'monaco-grand-prix',
    name: 'Monaco Grand Prix (Yacht Week)',
    location: 'Port Hercules, Monaco',
    port: 'Port Hercules',
    country: 'Monaco',
    region: 'French Riviera',
    month: 5,
    startDay: 22,
    durationDays: 4,
    type: 'superyacht',
    tier: 'major',
    description: 'Not a boat show, but 100+ superyachts dock for the F1 weekend. Massive provisioning demand.',
    logistics: 'Extreme road closures — circuit setup begins 6 weeks before. All deliveries via A8 and La Turbie entrance. Night deliveries only Thu-Sun. Massive demand for provisions, wine, and catering supplies.',
  },
  {
    id: 'fastnet-race',
    name: 'Rolex Fastnet Race',
    location: 'Cherbourg / Cowes',
    port: 'Royal Ocean Racing Club',
    country: 'UK / France',
    region: 'English Channel',
    month: 7,
    startDay: 22,
    durationDays: 7,
    type: 'regatta',
    tier: 'major',
    description: 'Iconic 695nm offshore race. 400+ entries, alternates start/finish between Cowes and Cherbourg.',
    logistics: 'Pre-race deliveries to Cowes or Cherbourg depending on year. Post-race support at finish port. Ferry crossings for vehicles.',
  },
  {
    id: 'kings-cup-palma',
    name: 'Copa del Rey Mapfre',
    location: 'Real Club Nautico, Palma',
    port: 'Port de Palma',
    country: 'Spain',
    region: 'Balearic Islands',
    month: 7,
    startDay: 29,
    durationDays: 6,
    type: 'regatta',
    tier: 'major',
    description: 'Spain\'s most prestigious regatta. 100+ boats including superyachts, with Royal patronage.',
    logistics: 'Peak summer — ferry bookings essential. Real Club Nautico quayside access for deliveries. Marina full — coordinate berth allocation with race office.',
  },
  {
    id: 'giraglia-rolex-cup',
    name: 'Giraglia Rolex Cup',
    location: 'Saint-Tropez to Genoa',
    port: 'Port de Saint-Tropez',
    country: 'France / Italy',
    region: 'Mediterranean',
    month: 6,
    startDay: 9,
    durationDays: 7,
    type: 'regatta',
    tier: 'regional',
    description: 'Classic Mediterranean offshore race from Saint-Tropez round La Giraglia rock to Genoa.',
    logistics: 'Start in Saint-Tropez, finish in Genoa. Support deliveries needed at both ends. See Saint-Tropez and Genoa logistics notes.',
  },
  {
    id: 'round-island-race',
    name: 'Round the Island Race',
    location: 'Cowes, Isle of Wight',
    port: 'Royal Yacht Squadron',
    country: 'UK',
    region: 'South Coast',
    month: 6,
    startDay: 29,
    durationDays: 1,
    type: 'regatta',
    tier: 'regional',
    description: 'Largest yacht race by fleet size — 1,500+ entries around the Isle of Wight.',
    logistics: 'One-day event but preparation deliveries in the week before. Same IOW ferry logistics as Cowes Week. Very busy weekend — book early.',
  },

  // ─── SUPERYACHT INDUSTRY ────────────────────────────────────────────────

  {
    id: 'metstrade',
    name: 'METSTRADE',
    location: 'RAI Amsterdam, Netherlands',
    port: 'N/A — Exhibition Centre',
    country: 'Netherlands',
    region: 'North Holland',
    month: 11,
    startDay: 18,
    durationDays: 3,
    type: 'trade_show',
    tier: 'major',
    description: 'World\'s largest marine equipment trade show. B2B only, 1,600+ exhibitors.',
    logistics: 'RAI has dedicated loading docks — book slot via Exhibitor Portal. Good motorway access (A10). Parking at P1 for commercial vehicles.',
  },
  {
    id: 'superyacht-cup-palma',
    name: 'The Superyacht Cup Palma',
    location: 'Real Club Nautico, Palma',
    port: 'Port de Palma',
    country: 'Spain',
    region: 'Balearic Islands',
    month: 6,
    startDay: 19,
    durationDays: 4,
    type: 'regatta',
    tier: 'regional',
    description: 'The original superyacht regatta, 25+ years running.',
    logistics: 'Same logistics as Palma Superyacht Show. Ferry access from Barcelona or Valencia. Real Club Nautico has good quayside access for deliveries.',
  },

  // ─── REGIONAL SHOWS ──────────────────────────────────────────────────────

  {
    id: 'london-boat-show',
    name: 'London Boat Show',
    location: 'ExCeL London',
    port: 'N/A — Exhibition Centre',
    country: 'UK',
    region: 'London',
    month: 1,
    startDay: 10,
    durationDays: 10,
    type: 'boat_show',
    tier: 'regional',
    description: 'UK\'s main indoor boat show at ExCeL London.',
    logistics: 'ExCeL has excellent loading dock facilities. DLR Custom House station. Use Royal Victoria Dock entrance for commercial vehicles. Congestion charge and ULEZ apply.',
  },
  {
    id: 'barcelona-boat-show',
    name: 'Barcelona International Boat Show',
    location: 'Port Vell, Barcelona',
    port: 'Port Vell',
    country: 'Spain',
    region: 'Catalonia',
    month: 10,
    startDay: 12,
    durationDays: 5,
    type: 'boat_show',
    tier: 'regional',
    description: 'Spain\'s largest nautical event, 700+ brands in Port Vell.',
    logistics: 'Barcelona ZBE (low emission zone) — check vehicle requirements. Port Vell access via Moll de la Fusta. Good rail freight connections.',
  },
  {
    id: 'antibes-yacht-show',
    name: 'Antibes Yacht Show',
    location: 'Port Vauban, Antibes',
    port: 'Port Vauban',
    country: 'France',
    region: 'French Riviera',
    month: 4,
    startDay: 10,
    durationDays: 3,
    type: 'superyacht',
    tier: 'regional',
    description: 'Pre-season superyacht show focused on refit and services. Good industry networking.',
    logistics: 'Port Vauban is Europe\'s largest marina. Good access from A8 autoroute. Deliver to Quai Camille Rayon. Parking at Fort Carré.',
  },
  {
    id: 'la-rochelle-boat-show',
    name: 'Grand Pavois La Rochelle',
    location: 'Port des Minimes, La Rochelle',
    port: 'Port des Minimes',
    country: 'France',
    region: 'Atlantic Coast',
    month: 9,
    startDay: 26,
    durationDays: 6,
    type: 'boat_show',
    tier: 'regional',
    description: 'France\'s largest in-water boat show on the Atlantic coast. 750+ exhibitors.',
    logistics: 'Good access via A10 motorway. Port des Minimes is 3km from town centre. Dedicated exhibitor parking. Bridge access may have height restrictions.',
  },
  {
    id: 'hanseboot-hamburg',
    name: 'hanseboot Hamburg',
    location: 'Hamburg Messe, Germany',
    port: 'N/A — Exhibition Centre',
    country: 'Germany',
    region: 'Northern Germany',
    month: 10,
    startDay: 19,
    durationDays: 9,
    type: 'boat_show',
    tier: 'regional',
    description: 'Northern Europe\'s largest boat show. Strong sailing and motorboat focus.',
    logistics: 'Hamburg Messe has good rail and road access. Use Hall A loading docks. Pre-book exhibitor vehicle passes.',
  },
  {
    id: 'viareggio-versilia-yachting',
    name: 'Versilia Yachting Rendez-vous',
    location: 'Viareggio, Italy',
    port: 'Porto di Viareggio',
    country: 'Italy',
    region: 'Tuscany',
    month: 5,
    startDay: 9,
    durationDays: 4,
    type: 'superyacht',
    tier: 'regional',
    description: 'Growing superyacht event in Italy\'s shipbuilding heartland (Benetti, Azimut, Perini Navi).',
    logistics: 'Autostrada A12 access. Viareggio is a major shipyard town — good marine logistics infrastructure. ZTL restrictions in harbour area.',
  },
  {
    id: 'athens-boat-show',
    name: 'Athens International Boat Show',
    location: 'Faliro Marina, Athens',
    port: 'Faliro Marina',
    country: 'Greece',
    region: 'Attica',
    month: 4,
    startDay: 28,
    durationDays: 5,
    type: 'boat_show',
    tier: 'regional',
    description: 'Greece\'s premier boat show covering the Eastern Mediterranean market.',
    logistics: 'Faliro is near Piraeus port — good for incoming freight from ferries. Athens ring road (Attiki Odos) access. Parking at SEF complex.',
  },
  {
    id: 'croatia-boat-show',
    name: 'Croatia Boat Show',
    location: 'Split, Croatia',
    port: 'ACI Marina Split',
    country: 'Croatia',
    region: 'Dalmatia',
    month: 4,
    startDay: 13,
    durationDays: 4,
    type: 'boat_show',
    tier: 'regional',
    description: 'Central Adriatic boat show in Croatia\'s growing charter hub.',
    logistics: 'Split has good ferry connections from Ancona, Italy. ACI Marina on the west side of the peninsula. Limited parking — use Sukoišan car park.',
  },
  {
    id: 'turkish-yacht-show',
    name: 'Yacht & Boat Show Tuzla',
    location: 'Viaport Marina, Istanbul',
    port: 'Viaport Marina Tuzla',
    country: 'Turkey',
    region: 'Sea of Marmara',
    month: 3,
    startDay: 6,
    durationDays: 5,
    type: 'boat_show',
    tier: 'regional',
    description: 'Turkey\'s main boat show, growing with Turkish shipbuilding sector.',
    logistics: 'Tuzla is on the Asian side of Istanbul — allow for bridge crossings. Good proximity to major Turkish shipyards. Customs clearance for EU goods at entry.',
  },

  // ─── RALLIES (EU/UK RELEVANT) ───────────────────────────────────────────

  {
    id: 'arc-rally',
    name: 'ARC (Atlantic Rally for Cruisers)',
    location: 'Las Palmas, Gran Canaria',
    port: 'Marina Las Palmas',
    country: 'Spain',
    region: 'Canary Islands',
    month: 11,
    startDay: 24,
    durationDays: 7,
    type: 'rally',
    tier: 'major',
    description: 'World\'s largest trans-ocean rally. Start in EU (Canaries). 200+ yachts. Huge provisioning demand before departure.',
    logistics: 'Las Palmas well connected by ferry from mainland Spain and by road freight to port. High demand for provisions, spare parts, and last-minute equipment Nov. Chandlery and marine supplies peak.',
  },
  {
    id: 'arc-europe',
    name: 'ARC Europe (Return)',
    location: 'Marina de Lagos, Portugal',
    port: 'Marina de Lagos',
    country: 'Portugal',
    region: 'Algarve',
    month: 5,
    startDay: 7,
    durationDays: 5,
    type: 'rally',
    tier: 'regional',
    description: 'Atlantic return crossing arrives in Lagos, Algarve. Support and provisioning at arrival.',
    logistics: 'Lagos marina in Algarve. Good road access from Faro airport (1hr). A22 motorway. Provisioning support on arrival. Portuguese customs straightforward for EU goods.',
  },

  // ─── UK REGIONAL ─────────────────────────────────────────────────────────

  {
    id: 'psp-boat-show',
    name: 'PSP Southampton Boat Show',
    location: 'Ocean Village, Southampton',
    port: 'Ocean Village Marina',
    country: 'UK',
    region: 'South Coast',
    month: 9,
    startDay: 15,
    durationDays: 10,
    type: 'boat_show',
    tier: 'regional',
    description: 'Major UK show alongside the International Boat Show.',
    logistics: 'Adjacent to main Southampton show. Same M27 access. Shared parking facilities with main show.',
  },
  {
    id: 'falmouth-week',
    name: 'Falmouth Week',
    location: 'Falmouth, Cornwall',
    port: 'Falmouth Harbour',
    country: 'UK',
    region: 'South West',
    month: 8,
    startDay: 10,
    durationDays: 8,
    type: 'regatta',
    tier: 'local',
    description: 'Major Cornish sailing event with racing and festivities.',
    logistics: 'A30/A39 road access. Limited HGV access in town centre. Falmouth Docks has commercial vehicle access. Plan longer journey times in peak summer.',
  },
  {
    id: 'dartmouth-regatta',
    name: 'Dartmouth Royal Regatta',
    location: 'Dartmouth, Devon',
    port: 'Dart Marina',
    country: 'UK',
    region: 'South West',
    month: 8,
    startDay: 22,
    durationDays: 3,
    type: 'regatta',
    tier: 'local',
    description: 'Historic regatta in the stunning River Dart.',
    logistics: 'Very narrow approach roads. Maximum vehicle width restrictions. Use higher ferry or Totnes road. Town car park for staging.',
  },
  {
    id: 'scottish-series',
    name: 'Scottish Series',
    location: 'Tarbert, Loch Fyne',
    port: 'Tarbert Harbour',
    country: 'UK',
    region: 'Scotland',
    month: 5,
    startDay: 24,
    durationDays: 3,
    type: 'regatta',
    tier: 'local',
    description: 'Scotland\'s premier sailing regatta on the stunning Clyde.',
    logistics: 'A83 from Glasgow (2.5hrs). Single track roads near Tarbert. Limited commercial vehicle access. Plan deliveries mid-week before event.',
  },
]

// Helper: Get events by month
export function getEventsByMonth(month: number): YachtEvent[] {
  return yachtEvents.filter(e => e.month === month)
}

// Helper: Get upcoming events (from a given month, wrap around)
export function getUpcomingEvents(currentMonth: number, count: number = 6): YachtEvent[] {
  const sorted = [...yachtEvents].sort((a, b) => {
    const aOffset = (a.month - currentMonth + 12) % 12
    const bOffset = (b.month - currentMonth + 12) % 12
    return aOffset - bOffset || a.startDay - b.startDay
  })
  return sorted.slice(0, count)
}

// Helper: Get events near a port/region
export function getEventsNearRegion(region: string): YachtEvent[] {
  const r = region.toLowerCase()
  return yachtEvents.filter(e =>
    e.region.toLowerCase().includes(r) ||
    e.country.toLowerCase().includes(r) ||
    e.location.toLowerCase().includes(r)
  )
}

// Helper: Get major events only
export function getMajorEvents(): YachtEvent[] {
  return yachtEvents.filter(e => e.tier === 'major')
}

// Month names for display
export const monthNames = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
]
